# Generated by Django 5.1.2 on 2024-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gender',
            name='value',
            field=models.CharField(choices=[('man', 'мужчина'), ('woman', 'женщина')], default='man', max_length=10),
        ),
    ]
