# Generated by Django 5.1.3 on 2024-11-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_gender_title_gender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('wholesaler', 'Wholesaler'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
