# Generated by Django 5.1.3 on 2024-11-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='gender',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
