# Generated by Django 5.1.3 on 2024-11-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_gender_name_remove_user_role_gender_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='title',
        ),
        migrations.AddField(
            model_name='gender',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('wholesaler', 'Wholesaler'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
