# Generated by Django 5.0.6 on 2024-05-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dyson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.dyson'),
        ),
    ]
