# Generated by Django 5.0.6 on 2024-06-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_brand_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='product.brand'),
            preserve_default=False,
        ),
    ]
