# Generated by Django 5.1.1 on 2024-09-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_label_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='label',
        ),
    ]
