# Generated by Django 5.1.1 on 2024-09-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_label_color_title_remove_color_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='title',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='key',
            new_name='value',
        ),
    ]
