# Generated by Django 5.1.1 on 2024-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_title_color_label_rename_key_color_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
