# Generated by Django 5.0.6 on 2024-05-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_name_category_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='foreign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.foreign'),
            preserve_default=False,
        ),
    ]
