# Generated by Django 5.0.6 on 2024-05-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_foreign_color_foreign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='foreign',
        ),
        migrations.DeleteModel(
            name='Foreign',
        ),
    ]
