# Generated by Django 5.1.1 on 2024-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
