# Generated by Django 5.0.6 on 2024-08-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
