# Generated by Django 5.0.6 on 2024-08-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_product_of_the_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_of_the_day',
            new_name='is_product_of_the_day',
        ),
    ]
