# Generated by Django 5.1.1 on 2024-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_brand_value_alter_category_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Значение категории'),
        ),
    ]
