# Generated by Django 5.0.6 on 2024-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_product_of_the_day',
            field=models.BooleanField(),
        ),
    ]
