# Generated by Django 5.0.6 on 2024-08-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_is_product_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_product_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
