# Generated by Django 5.0.6 on 2024-08-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_image2_product_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
    ]
