# Generated by Django 5.0.6 on 2024-08-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
