# Generated by Django 5.1.1 on 2024-10-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_characteristic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
