# Generated by Django 5.0.6 on 2024-09-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_category_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
