# Generated by Django 5.1.2 on 2024-10-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.characteristic'),
        ),
    ]
