# Generated by Django 5.1.3 on 2024-11-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_productcharacteristic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCharacteristic',
        ),
    ]
