# Generated by Django 5.1.2 on 2024-11-24 11:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_banner_url_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image1'),
        ),
    ]
