# Generated by Django 5.1.2 on 2024-11-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
