# Generated by Django 5.1.2 on 2024-11-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
