# Generated by Django 5.0.6 on 2024-06-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='tires',
            new_name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
