# Generated by Django 4.2.9 on 2024-06-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem'),
    ]

    operations = [
    ]
