# Generated by Django 5.0.6 on 2024-08-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_paymentmethod_alter_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.paymentmethod'),
            preserve_default=False,
        ),
    ]
