# Generated by Django 5.0.6 on 2024-08-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_order_ordered_at_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='promotion',
        ),
    ]
